# Generated by Django 3.1.5 on 2021-01-06 11:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('real_name', models.CharField(max_length=16)),
                ('age', models.IntegerField(max_length=3)),
                ('sex', models.BooleanField(choices=[('男', False), ('女', True)], default='男')),
                ('phone_number', models.CharField(max_length=11)),
                ('address', models.CharField(max_length=16)),
                ('intro', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=16)),
                ('password', models.CharField(max_length=16)),
                ('user_detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oj.userdetail')),
            ],
        ),
    ]
