# Generated by Django 3.1.5 on 2021-01-06 11:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('oj', '0003_auto_20210106_1937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_detail',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oj.userdetail'),
        ),
    ]
