# Generated by Django 3.1.5 on 2021-01-06 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oj', '0004_auto_20210106_1938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetail',
            name='sex',
            field=models.BooleanField(choices=[(False, '男'), (True, '女')], default=False),
        ),
    ]
