# Generated by Django 3.1.5 on 2021-01-07 02:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oj', '0005_auto_20210106_2001'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='user_detail',
        ),
        migrations.DeleteModel(
            name='UserDetail',
        ),
    ]
