# Generated by Django 3.1.5 on 2021-01-07 04:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('oj', '0006_auto_20210107_1010'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contest_name', models.CharField(max_length=16)),
                ('contest_start_time', models.DateTimeField()),
                ('contest_end_time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('problem_name', models.CharField(max_length=16)),
                ('problem_content', models.CharField(max_length=1024)),
                ('problem_memory_limit', models.IntegerField()),
                ('problem_time_limit', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.CharField(default='', max_length=256),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.IntegerField()),
                ('memo', models.CharField(max_length=16)),
                ('contest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oj.contest')),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oj.problem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oj.user')),
            ],
        ),
        migrations.AddField(
            model_name='contest',
            name='problem_list',
            field=models.ManyToManyField(to='oj.Problem'),
        ),
    ]
