# Generated by Django 3.1.5 on 2021-01-07 11:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('oj', '0008_user_is_admin'),
    ]

    operations = [
        migrations.CreateModel(
            name='Code',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_location', models.CharField(max_length=256)),
                ('contest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oj.contest')),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oj.problem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oj.user')),
            ],
        ),
    ]
